//{{ .JobName }} JOB (ACCT),'{{ .JobName }}',CLASS=A,MSGCLASS=A,MSGLEVEL=(1,1)
//STEP1    EXEC IGYWCL
//COBOL.SYSIN DD *
{{ .CobolSource }}
/*
//GO      EXEC PGM=COBOL
//STEPLIB DD DSN={{ .DatasetPrefix }}.LOAD,DISP=SHR
//SYSPRINT DD SYSOUT=*
//SYSOUT   DD SYSOUT=*
