//{{ .JobName }} JOB (ACCT),'HELLO',CLASS=A,MSGCLASS=A,MSGLEVEL=(1,1)
//STEP1    EXEC IGYWCL
//COBOL.SYSIN   DD *
{{ .COBOLSource }}
/*
//LKED.SYSLMOD  DD DISP=SHR,DSN=&&LOAD
//GO.SYSOUT     DD SYSOUT=*
//
