config:
  profile: zosmf

datasets:
  jcl: Z71405.HELLO.GRC.JCL
  src: Z71405.HELLO.GRC.SRC
  loadlib: Z71405.LOAD

jobs:
  - name: hello
    step: execute
    source: hello.cbl

  - name: hello2
    step: execute
    source: hello.cbl

  - name: hello3
    step: execute
    source: hello.cbl
    depends_on: [hello, hello2]
