config:
  profile: zosmf
  concurrency: 3

datasets:
  jcl: IBMUSER.HELLO.GRC.JCL
  src: IBMUSER.HELLO.GRC.SRC
  loadlib: IBMUSER.LOAD

jobs:
  - name: compile-hello
    step: compile
    inputs:
      - name: sysin
        path: src://hello.cbl
      # optional: add SYSLIB if copybooks are needed
      # - name: syslib
      #   path: zos://USER.COBOL.COPYLIB
      #   object deck goes out via SYSLIN DD
    outputs:
      - name: syslin
        path: temp://hello.obj
      # Optional: Add DCB/SPACE if needed for object deck dataset
      # Optional: Capture compiler listing
      # - name: sysprint
      #   path: temp://compile-hello.list

  - name: link-hello
    step: linkedit
    depends_on: [link-hello]
    inputs:
      - name: syslin
        path: temp://hello.obj


  - name: run-hello
    step: execute
    depends_on: [link-hello]
