config:
  profile: zosmf
  concurrency: 3
  defaults:
    compiler:
      pgm: IGYCRCTL
      parms: 'OBJECT,NODECK,LIB'
      steplib: IGY.V6R4M0.SIGYCOMP
    linker:
      pgm: IEWL
      parms: 'LIST,MAP,XREF'
      # steplib: optional - only if linker isn't in system LNKLST

datasets:
  jcl: IBMUSER.HELLO.GRC.JCL
  src: IBMUSER.HELLO.GRC.SRC
  loadlib: IBMUSER.LOAD

jobs:
  - name: CMPHELLO
    type: compile
    inputs:
      - name: SYSIN
        path: src://hello.cbl
    outputs:
      - name: SYSLIN
        path: zos-temp://hello.obj

  - name: LNKHELLO
    type: linkedit
    depends_on: [CMPHELLO]
    program: HELLO
    inputs:
      - name: SYSLIN
        path: zos-temp://hello.obj


  - name: RUNHELLO
    type: execute
    program: HELLO
    depends_on: [LNKHELLO]
