config:
  profile: zosmf
  defaults:
    compiler:
      pgm: IGYCRCTL
      steplib: IGY.V6R4M0.SIGYCOMP
    linker:
      pgm: IEWL
      parms: 'LIST,MAP,XREF'

datasets:
  jcl: IBMUSER.VSAMCSV.GRC.JCL
  src: IBMUSER.VSAMCSV.GRC.SRC
  loadlib: IBMUSER.LOAD

jobs:
  # - name: COMPILE
  #   type: compile
  #   inputs:
  #     - name: SYSIN
  #       path: src://vsamcsv.cbl
  #   outputs:
  #     - name: SYSLIN
  #       path: zos-temp://vsamcsv.obj
  #
  # - name: LINK
  #   depends_on: [COMPILE]
  #   type: linkedit
  #   program: VSAMCSV
  #   inputs:
  #     - name: SYSLIN
  #       path: zos-temp://vsamcsv.obj

  - name: RUN
    # depends_on: [LINK]
    type: execute
    program: VSAMCSV
    inputs:
      - name: VSAMIN
        path: zos://IBMUSER.VSAMDEMO.KSDS
    outputs:
      - name: CSVOUT
        path: zos-temp://vsam_extract.csv

  - name: LOADCSV
    depends_on: [RUN]
    type: shell
    with:
      inline: |
        echo "Writing to '$GRACE_OUTPUT_LOCALCPY'"
        cp "$GRACE_INPUT_CSVDL" "$GRACE_OUTPUT_LOCALCPY"
    inputs:
      - name: CSVDL
        path: zos-temp://vsam_extract.csv
        encoding: text
    outputs:
      - name: LOCALCPY
        path: file://vsam_extract.csv
